name: BookVerse
description: A premium Flutter book reading application.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # State management
  provider:
  http:

  # Firebase Authentication
  firebase_core:
  firebase_auth:
  cloud_firestore:

  uuid: 

  # Sign in with Google
  google_sign_in:

  # Typography
  google_fonts:

  # Local storage
  path_provider:
  permission_handler:
  path:
  external_path:
  flutter_stripe:
  cloud_functions:

  shared_preferences:

  # Images
  cached_network_image:
  palette_generator:

  # Loading states
  shimmer:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

  # App Launcher Icon
  flutter_launcher_icons: 


# ============================================================
# APP ICON CONFIGURATION
# ============================================================

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "asset/logic.png"
  min_sdk_android: 21
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - asset/li.png
    - asset/book.png
    - asset/logic.png

  fonts:
    - family: BrittanySignature
      fonts:
        - asset: asset/Fonts/BrittanySignature.ttf

    - family: Dancing
      fonts:
        - asset: asset/Fonts/Dancig.ttf